### ISSUE TITLE
cluster-admin is unable to install MachineConfig resources

### ISSUE THREAD

**Issue by chkp-alexgl** [openshift/managed-cluster-validating-webhooks#193]
Hello,
Our app (running on OpenShift as a DaemonSet) requires installation of certain Operating System packages on each node. In a nutshell, we need 'kernel-devel' in order to dynamically compile code that needs to be fully compatible with the kernel running on the node.
In order to automate installation of these packages on OpenShift clusters, we include MachineConfig resources in our Helm chart. E.g.:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "worker"
  name: 99-worker-kernel-devel
spec:
  config:
    ignition:
      version: 3.1.0
  extensions:
    - kernel-devel
```

However, since recently, the installation (performed by cluster-admin user, on a ROSA cluster) started to fail, with the following error message:

`"admission webhook "regular-user-validation.managed.openshift.io" denied the request: Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support"`

After searching online a bit, this seems to be related to this change (essentially preventing cluster-admin from creating MachineConfig resources):
https://github.com/openshift/managed-cluster-validating-webhooks/pull/192

Is there a different way to achieve what we need (installation of OS packages on all nodes)? Or a workaround? Maybe a way to exclude cluster-admin from this validation?

Thanks!
Alex
